### ISSUE TITLE
[BUG] getPlaylist not working on repl.it 

### ISSUE THREAD

**Issue by Colonel-Ltd** [VincentJonathan/scrape-yt#24]
SyntaxError: Unexpected token } in JSON at position 10674
    at JSON.parse (<anonymous>)
    at Object.parseGetPlaylist (/home/runner/Bot/node_modules/scrape-yt/dist/common/parser.js:274:36)
    at /home/runner/Discord-MusicBot/node_modules/scrape-yt/dist/index.js:162:64
    at step (/home/runner/Discord-MusicBot/node_modules/scrape-yt/dist/index.js:54:23)

**Comment by SuspiciousLookingOwl** [comment]
Please provide more information, which id of playlist are you trying to get?

**Comment by Colonel-Ltd** [comment]
PL9bw4S5ePsEEqCMJSiYZ-KTtEjzVy0YvK

**Comment by SuspiciousLookingOwl** [comment]
I can't reproduce, are you using VPN / running it on a VPS? This can happens sometime if you are using VPN or running on a VPS.

**Comment by Colonel-Ltd** [comment]
i use free host like repl.it

**Comment by SuspiciousLookingOwl** [comment]
Just tried it on repl.it and it's indeed not working, I'm still not sure why, this sometimes also happens when using VPN, need further investigation.

Don't expect update anytime soon though because I'm currently busy working on other project, and planning to rewrite this library after I'm done with my other project.

**Comment by Colonel-Ltd** [comment]
OK
