### ISSUE TITLE
.search() error for video without publish date

### ISSUE THREAD

**Issue by KareemH** [VincentJonathan/scrape-yt#3]
![image](https://user-images.githubusercontent.com/40571613/79935302-944c3c00-8422-11ea-8354-be3060e0459c.png)
The youtube scraper was working perfectly fine before and using the maxRetryCount logic worked fine as well. But now, the addition of simpleText makes it work not at all. Could you please revert it?

**Comment by SuspiciousLookingOwl** [comment]
You can install old version instead with `npm install scrape-yt@1.0.7`

Can you reproduce it consistently? Is there any specific keyword of search? That will be helpful for me to fix this.

**Comment by SuspiciousLookingOwl** [comment]
Okay i found what causes this, turns out not all video have published date for some reason..
![image](https://user-images.githubusercontent.com/32597776/79946960-3576d900-849b-11ea-850d-ab389d1ec215.png)

a12c5a358dc7cf69629c8bd81c07301c53fd79cf should fixed it. Published the update to npm (v1.0.10)

Thank you for reporting this bug! If the issue still persists, feel free to open it again :)
